### PR TITLE
Update azuresearch.js

### PR DESCRIPTION
**Pull request by dalibormesaric**
Tags were not extracted from posts and pushed to index, so hopefully this fixes that.

### CODE REVIEW

**Comment by dalibormesaric** [comment]
ping @artchen

**Comment by artchen** [comment]
Thanks for the fix.

**Comment by dalibormesaric** [comment]
Could you update your npm package with this update? Thanks! @artchen

**Comment by artchen** [comment]
Yep, I released a new version to npm. Thanks for the reminder.

**Pull request merged**
